---
- hosts: all
  tasks:
    - name: Adiciona Diretorios Docker
      become: yes
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Instala Dependencias
      become: yes
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - git-all
        - net-tools
        - libselinux-python
        - libselinux-python
    
    - name: Desabilita SELINUX
      become: yes
      selinux:
        state: disabled
 
    - name: Define SELINUX para modo permissivo até a maquina reiniciar
      become: yes
      command: setenforce 0
      ignore_errors: true
      changed_when: false

    - name: Inicia Docker
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Instala Docker-Compose
      become: yes
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      
    - name: Configura Atalho Docker-Compose
      become: yes
      shell:
        cmd: sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        
    - name: Instala Promethues
      become: yes
      git:
        repo: https://github.com/kaihendry/pingprom.git
        dest: /home/monitoramento/pingprom
        force: yes
    
    - name: Copia targets.yml personalizado
      become: yes 
      copy:
        src: /home/vagrant/targets.yml
        dest: /home/monitoramento/pingprom/prometheus
        mode: 0644
        remote_src: yes
        force: yes
        
    - name: Inicia Monitoramento
      remote_user: vagrant
      shell: sudo make -C /home/monitoramento/pingprom/

      
